### ISSUE TITLE
论文

### ISSUE THREAD

**Issue by y1291446120** [zhengziqiang/CAIS#1]
请问有没有论文啊?想学习一下

**Comment by zhengziqiang** [comment]
我们投稿了期刊，正在审稿中，您可以给我一个邮箱，我给您发一下。

**Comment by y1291446120** [comment]
您好，我是之前在github上评论您的项目，找您要论文的那个学生，这是我的邮箱1291446120@qq.com，谢谢您!

--------------原始邮件--------------
发件人："zhengziqiang "<notifications@github.com&gt;;
发送时间：2020年10月4日(星期天) 中午1:31
收件人："zhengziqiang/CAIS" <CAIS@noreply.github.com&gt;;
抄送："y1291446120 "<08153172@cumt.edu.cn&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [zhengziqiang/CAIS] 论文 (#1)
-----------------------------------

 

 
我们投稿了期刊，正在审稿中，您可以给我一个邮箱，我给您发一下。

**Comment by y1291446120** [comment]
您好，这是我的邮箱1291446120@qq.com，谢谢您
